name: goreleaser

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run GoReleaser Cross
        run: |
          docker run \
            --rm \
            --privileged \
            -e CGO_ENABLED=1 \
            -e GITHUB_TOKEN=${GITHUB_TOKEN} \
            -v /Users/kyjahkeys/.colima/docker.sock:/var/run/docker.sock \
            -v `pwd`:/go/src/github.com/DataDog/temporalite \
            -v `pwd`/sysroot:/sysroot \
            -w /go/src/github.com/DataDog/temporalite \
            goreleaser/goreleaser-cross:v1.18.2 \
            --rm-dist
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
